services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: leads_user
      POSTGRES_PASSWORD: leads_pass
      POSTGRES_DB: leads_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leads_user -d leads_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  landings:
    build:
      context: .
      dockerfile: landings/Dockerfile
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql+asyncpg://leads_user:leads_pass@postgres:5432/leads_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: change-me-in-production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  #core:
   # build:
    #  context: .
     # dockerfile: core/Dockerfile
   # ports:
    #  - "8002:8002"
#    environment:
 #     DATABASE_URL: postgresql+asyncpg://leads_user:leads_pass@postgres:5432/leads_db
  #    REDIS_URL: redis://redis:6379
 #     JWT_SECRET: change-me-in-production
 #   depends_on:
 #     postgres:
 #       condition: service_healthy
 #     redis:
 #       condition: service_healthy

  buyo:                              
    build: ../buyo-internship-template
    ports:
      - "8000:8000"
    environment:
      DB__HOST: postgres
      DB__PORT: 5432
      DB__NAME: buyo_db
      DB__USER: leads_user
      DB__PASSWORD: leads_pass
      JWT__SECRET_KEY: your-secret
      REDIS__HOST: redis
      REDIS__PORT: 6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: